title: What-Secuirty
description: About Security
baseurl: "/"
url: https://www.what-security.co.uk
permalink: ':title/'
blog_theme: light

# Profile information
name: Robert Wiggins
tagline: Finding Security Holes Everywhere ¯\_(ツ)_/¯
about-description: I am a full time IT Guy and a bug bounty enthusiast.
pic: 79.jpg 

# Contact links
email: txt3rob@gmail.com 
website: what-security.co.uk 
github: random-robbie 
twitter: '@random_robbie'



# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
